from sqlalchemy import Column, Integer, String, ForeignKey, create_engine, Text
from sqlalchemy.ext.declarative import declarative_base
from config import host, user, password, db_name, port


db = 'mysql+pymysql://{0}:{1}@{2}:{3}/{4}'.format(user, password, host, port, db_name)
engine = create_engine(db)

Base = declarative_base()


class Reestr(Base):
    __tablename__ = 'reestr'

    id = Column(Integer, primary_key=True)
    id_gkh = Column(Integer, nullable=True)
    region_id = Column(String(255), nullable=True)
    area_id = Column(String(200), nullable=True)
    city_id = Column(String(200), nullable=True)
    street_id = Column(String(200), nullable=True)
    shortname_region = Column(String(200), nullable=True)
    formalname_region = Column(String(200), nullable=True)
    shortname_area = Column(String(200), nullable=True)
    formalname_area = Column(String(200), nullable=True)
    shortname_city = Column(String(200), nullable=True)
    formalname_city = Column(String(200), nullable=True)
    shortname_street = Column(String(200), nullable=True)
    formalname_street = Column(String(200), nullable=True)
    house_number = Column(String(200), nullable=True)
    building = Column(String(200), nullable=True)
    block = Column(String(200), nullable=True)
    letter = Column(String(200), nullable=True)
    address = Column(String(200), nullable=True)
    houseguid = Column(String(200), nullable=True)
    management_organization_id = Column(String(200), nullable=True)
    built_year = Column(String(200), nullable=True)
    exploitation_start_year = Column(String(200), nullable=True)
    project_type = Column(String(200), nullable=True)
    house_type = Column(String(200), nullable=True)
    is_alarm = Column(String(200), nullable=True)
    method_of_forming_overhaul_fund = Column(String(200), nullable=True)
    floor_count_max = Column(String(200), nullable=True)
    floor_count_min = Column(String(200), nullable=True)
    entrance_count = Column(String(200), nullable=True)
    elevators_count = Column(String(200), nullable=True)
    energy_efficiency = Column(String(200), nullable=True)
    quarters_count = Column(String(200), nullable=True)
    living_quarters_count = Column(String(200), nullable=True)
    unliving_quarters_count = Column(String(200), nullable=True)
    area_total = Column(String(200), nullable=True)
    area_residential = Column(String(200), nullable=True)
    area_non_residential = Column(String(200), nullable=True)
    area_common_property = Column(String(200), nullable=True)
    area_land = Column(String(200), nullable=True)
    parking_square = Column(String(200), nullable=True)
    playground = Column(String(200), nullable=True)
    sportsground = Column(String(200), nullable=True)
    other_beautification = Column(Text, nullable=True)
    foundation_type = Column(String(200), nullable=True)
    floor_type = Column(String(200), nullable=True)
    wall_material = Column(String(255), nullable=True)
    basement_area = Column(String(200), nullable=True)
    chute_type = Column(String(200), nullable=True)
    chute_count = Column(String(200), nullable=True)
    electrical_type = Column(String(200), nullable=True)
    electrical_entries_count = Column(String(200), nullable=True)
    heating_type = Column(String(200), nullable=True)
    hot_water_type = Column(String(200), nullable=True)
    cold_water_type = Column(String(200), nullable=True)
    sewerage_type = Column(String(200), nullable=True)
    sewerage_cesspools_volume = Column(String(200), nullable=True)
    gas_type = Column(String(200), nullable=True)
    ventilation_type = Column(String(200), nullable=True)
    firefighting_type = Column(String(200), nullable=True)
    drainage_type = Column(String(200), nullable=True)
    # citizen_count = Column(String(200), nullable=True)


Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)